### ISSUE TITLE
Magic Anvil - New TileEntity to Upgrade Items Rarity

### ISSUE THREAD

**Issue by MasterEnderman** [KenyMylankca/EnhancedArmaments#8]
A simple tileentity that will require different items by respect to the item to upgrade it. Will have a GUI just like the furnace. Will have chance by respect to the items quality and the process will be shown too. Success(rarity upgraded), or fail(item gonna be destroyed)

Basic to Uncommon: %60 chance. Required Item: Spider Eye
Uncommon to Rare: %40 chance. RI: Fermented Spider Eye
Rare to Ultra Rare: %20 chance. RI: Magma Cream
Ultra Rare to Legendary: %10 chance. RI: Nether Wart
Legendary to Archaic: %5 chance. RI: Dried Kelp

**Comment by KenyMylankca** [comment]
did you know the rarity changing command? /changerarity <rarity id>

**Comment by MasterEnderman** [comment]
i would appreaciate a method for survivalmode so the player can reforge it to change the rarity in a legit way, with a cost.

**Comment by KenyMylankca** [comment]
ah, with a cost in survival, i see. what i think is it would be unfunny but ill consider it... thank you

**Comment by RavenChan1023** [comment]
Right now the only way to get better modifiers that I know of is to use an uncrafting table and repeatedly uncraft and recraft the same item over and over again.

**Comment by SonicX8000** [comment]
If this is still being considered... I wonder if this is possible...

The item could have a level requirement in order to be eligible for a rarity upgrade... however at a cost.

If you wish to upgrade the item's rarity... you will have to forfeit all the XP... as well as any unlocked Abilities and unused Ability Tokens, if they're still called that... for that item. It'll be as if you got/crafted the item but instead of getting a random rarity... it's current rarity will be increased by one stage, and it'll have 0 XP and no Abilities or Tokens.

The level required and such could be configurable in a way. The success/fail chance that @MasterEnderman mentioned could also apply depending on the level with a minimum level needed, and recommended levels needed.

*Example*
Level 04 - Item may be destroyed or the upgrade fails when attempting to upgrade it's rarity. Success/failure will reset item's XP & Abilities, etc.

Level 07 - Item will no longer have a chance to be destroyed but there's a chance that the upgrade fails when attempting to upgrade it's rarity. Success/failure will reset item's XP & Abilities, etc.

Level 10 and up - Item is guaranteed a rarity upgrade. Success will reset item's XP & Abilities, etc.

**Comment by KenyMylankca** [comment]
it's time to realize this. but i need to update to 1.13 with fully working code first. then i'll make this anvil thing.

**Comment by KenyMylankca** [comment]
this is done in https://github.com/KenyMylankca/HarshenUniverse/commit/7bfa6b94df5e720ab49744ad7919d7658a1610ec
